### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by razvandamian** [Zeroo000/Project-Zero#5]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

When you play a song, if you can put the thumbnail like that 
![image](https://user-images.githubusercontent.com/67657296/93253484-99c66c00-f79f-11ea-8ad2-177a6dcd7196.png) without black bars it would be cool, and if you can also to add the author who posted the video on play embed

**Describe alternatives you've considered**

**Additional context**

**Comment by razvandamian** [comment]
> :)' first issue

its a feature request not a issue

**Comment by Zeroo000** [comment]
Thank you for the Feature Request. I will keep this in mind, I'm currently in the process on modifying the whole Music Command. So stay tuned for the new look on Music Command! I am near on finishing it.

**Comment by razvandamian** [comment]
ok thanks for response i will close this feature request, you can open it and reanswer me any time!

**Comment by razvandamian** [comment]
i found something at static constructSongObj(video, voiceChannel, user) { go to thumbnails and there if you set the video.thumbnails.high.url to maxres.url for some songs it works fine but when you go to older songs a error appears, i tried to separate more of them like video.thumbnails.high.url || video.thumbnails.maxres.url but its not working, see if you find it out 👍

**Comment by razvandamian** [comment]
something?
